In [462]:
%load_ext autoreload
%autoreload 2

import time
import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import uniform, randint
from sklearn.preprocessing import MinMaxScaler
import xarray as xr
#import pymaise 



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [463]:
import psutil
import GPUtil

def get_gpu_utilization():
    # Get the list of available GPUs
    gpus = GPUtil.getGPUs()
    
    if len(gpus) == 0:
        print("No GPU found.")
        return
    
    for gpu in gpus:
        print(f"GPU {gpu.id}:")
        print(f"  - GPU name: {gpu.name}")
        print(f"  - GPU load: {gpu.load * 100:.2f}%")
        print(f"  - GPU memory total: {gpu.memoryTotal} MB")
        print(f"  - GPU memory used: {gpu.memoryUsed} MB")
        print(f"  - GPU memory free: {gpu.memoryFree} MB")
        print(f"  - GPU memory utilization: {gpu.memoryUtil * 100:.2f}%")
        print()

def main():
    # Print CPU utilization
    print("CPU utilization:", psutil.cpu_percent(interval=1))
    
    # Print GPU utilization
    get_gpu_utilization()

if __name__ == "__main__":
    main()


CPU utilization: 6.3
GPU 0:
  - GPU name: NVIDIA GeForce RTX 4090
  - GPU load: 100.00%
  - GPU memory total: 24564.0 MB
  - GPU memory used: 24212.0 MB
  - GPU memory free: 4.0 MB
  - GPU memory utilization: 98.57%

GPU 1:
  - GPU name: NVIDIA GeForce RTX 4090
  - GPU load: 100.00%
  - GPU memory total: 24564.0 MB
  - GPU memory used: 7678.0 MB
  - GPU memory free: 16538.0 MB
  - GPU memory utilization: 31.26%



In [464]:
from pyMAISE.datasets import load_anomaly
from pyMAISE.preprocessing import train_test_split, scale_data, one_hot_encode, SplitSequence
import pyMAISE as mai

In [465]:
%%time

global_settings = mai.init(
    problem_type=mai.ProblemType.CLASSIFICATION,   # Define a regression problem
    #cuda_visible_devices="-1"                  # Use CPU only/ Delete line when run on GPU
)

CPU times: user 50 µs, sys: 4 µs, total: 54 µs
Wall time: 59.8 µs


In [466]:
# call handler
input_path = "/home/jacc/pyMAISE/pyMAISE/datasets/DTL.npy"
output_path = "/home/jacc/pyMAISE/pyMAISE/datasets/DTL_labels.npy"
#print(mai.__file__)
#False, False, False: WORKS       X.shape = (1077, 4500, 14), Y.shape = (1077, 1)  one hot
#False, True, False: WORKS       X.shape = (1077, 4500, 14), Y.shape = (1077, 1)
#False, False, True:  ?      X.shape = (1077, 4500, 14), Y.shape = (1077, 4500, 1)
#False, True, True:   ?      X.shape = (1077, 4500, 14), Y.shape = (1077, 4500, 1)
#True, False, True: WORKS        X.shape = (4846500, 14), Y.shape = (4846500, 1)
#True, True, True: WORKS         X.shape = (4846500, 14), Y.shape = (4846500, 1)
cond1 = True
cond2 = False
cond3 = True
inputs, outputs = load_anomaly([input_path, output_path], cond1, cond2, cond3)


In [467]:
inputs

<xarray.DataArray (timesteps: 4846500, features: 14)>
array([[-6.07100e+00,  5.55120e+00, -1.42220e+00, ..., -4.60370e-02,
         2.17170e+03,  1.27100e+00],
       [-4.85030e+00,  4.33040e+00, -2.64290e+00, ...,  1.50000e-02,
         2.17250e+03, -1.33776e+01],
       [-4.85030e+00,  1.88890e+00, -1.42220e+00, ...,  4.55190e-02,
         2.17320e+03, -8.49500e+00],
       ...,
       [-2.17470e+00, -7.57620e+00, -3.39550e+00, ..., -1.07070e-01,
         2.17220e+03,  1.19730e+01],
       [-4.61620e+00, -3.91400e+00, -5.83700e+00, ..., -1.68110e-01,
         2.17180e+03,  9.53200e+00],
       [-3.39550e+00, -6.35550e+00, -5.83700e+00, ..., -4.60370e-02,
         2.17150e+03,  9.53200e+00]], dtype=float32)
Coordinates:
  * timesteps  (timesteps) int64 0 1 2 3 4 ... 4846496 4846497 4846498 4846499
  * features   (features) <U18 'A+IGBT-I: current' ... 'DV/DT'

In [468]:
outputs

<xarray.DataArray (timesteps: 4846500, features: 1)>
array([['Run'],
       ['Run'],
       ['Run'],
       ...,
       ['Fault'],
       ['Fault'],
       ['Fault']], dtype=object)
Coordinates:
  * timesteps  (timesteps) int64 0 1 2 3 4 ... 4846496 4846497 4846498 4846499
  * features   (features) <U5 'Class'

In [469]:
outputs = one_hot_encode(outputs)
outputs

<xarray.DataArray (timesteps: 4846500, features: 2)>
array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])
Coordinates:
  * timesteps  (timesteps) int64 0 1 2 3 4 ... 4846496 4846497 4846498 4846499
  * features   (features) object 'Class_Fault' 'Class_Run'

In [470]:
data = xr.concat([inputs, outputs], dim="features")
data

<xarray.DataArray (timesteps: 4846500, features: 16)>
array([[ -6.0710001 ,   5.55119991,  -1.42219996, ...,   1.27100003,
          0.        ,   1.        ],
       [ -4.85029984,   4.33039999,  -2.64289999, ..., -13.37759972,
          0.        ,   1.        ],
       [ -4.85029984,   1.88890004,  -1.42219996, ...,  -8.49499989,
          0.        ,   1.        ],
       ...,
       [ -2.17470002,  -7.57620001,  -3.39549994, ...,  11.97299957,
          1.        ,   0.        ],
       [ -4.61619997,  -3.91400003,  -5.83699989, ...,   9.53199959,
          1.        ,   0.        ],
       [ -3.39549994,  -6.35550022,  -5.83699989, ...,   9.53199959,
          1.        ,   0.        ]])
Coordinates:
  * timesteps  (timesteps) int64 0 1 2 3 4 ... 4846496 4846497 4846498 4846499
  * features   (features) object 'A+IGBT-I: current' ... 'Class_Run'

In [471]:
split_sequence = SplitSequence(
    10, 
    1, 
    0, 
    sequence_inputs=data.coords["features"].values[:-2], 
    sequence_outputs=data.coords["features"].values[-2:],
)
inputs, outputs = split_sequence.split(data)

inputs

<xarray.DataArray (samples: 4846491, timesteps: 10, features: 14)>
array([[[-6.07100010e+00,  5.55119991e+00, -1.42219996e+00, ...,
         -4.60369997e-02,  2.17169995e+03,  1.27100003e+00],
        [-4.85029984e+00,  4.33039999e+00, -2.64289999e+00, ...,
          1.49999997e-02,  2.17250000e+03, -1.33775997e+01],
        [-4.85029984e+00,  1.88890004e+00, -1.42219996e+00, ...,
          4.55190018e-02,  2.17319995e+03, -8.49499989e+00],
        ...,
        [-3.62960005e+00,  1.88890004e+00, -5.08440018e+00, ...,
         -4.60369997e-02,  2.17239990e+03, -1.17100000e+00],
        [-7.29180002e+00,  1.88890004e+00, -3.86360002e+00, ...,
          1.49999997e-02,  2.17230005e+03, -1.33781004e+01],
        [-7.29180002e+00,  3.10969996e+00, -2.64289999e+00, ...,
         -4.60369997e-02,  2.17280005e+03, -1.17100000e+00]],

       [[-4.85029984e+00,  4.33039999e+00, -2.64289999e+00, ...,
          1.49999997e-02,  2.17250000e+03, -1.33775997e+01],
        [-4.85029984e+00,  1.88890004e+00, -1.42219996e+00, ...,
          4.55190018e-02,  2.17319995e+03, -8.49499989e+00],
        [-7.29180002e+00,  1.88890004e+00, -1.42219996e+00, ...,
          4.55190018e-02,  2.17300000e+03, -2.31439991e+01],
...
        [-4.61619997e+00, -8.79699993e+00, -4.61619997e+00, ...,
          1.49999997e-02,  2.17180005e+03,  4.64900017e+00],
        [-2.17470002e+00, -7.57620001e+00, -3.39549994e+00, ...,
         -1.07069999e-01,  2.17219995e+03,  1.19729996e+01],
        [-4.61619997e+00, -3.91400003e+00, -5.83699989e+00, ...,
         -1.68109998e-01,  2.17180005e+03,  9.53199959e+00]],

       [[-7.05770016e+00, -7.57620001e+00, -3.39549994e+00, ...,
          1.06559999e-01,  2.17180005e+03,  7.09000015e+00],
        [-4.61619997e+00, -6.35550022e+00, -7.05770016e+00, ...,
         -4.60369997e-02,  2.17160010e+03,  7.09100008e+00],
        [-3.39549994e+00, -8.79699993e+00, -2.17470002e+00, ...,
         -4.60369997e-02,  2.17180005e+03,  1.19740000e+01],
        ...,
        [-2.17470002e+00, -7.57620001e+00, -3.39549994e+00, ...,
         -1.07069999e-01,  2.17219995e+03,  1.19729996e+01],
        [-4.61619997e+00, -3.91400003e+00, -5.83699989e+00, ...,
         -1.68109998e-01,  2.17180005e+03,  9.53199959e+00],
        [-3.39549994e+00, -6.35550022e+00, -5.83699989e+00, ...,
         -4.60369997e-02,  2.17150000e+03,  9.53199959e+00]]])
Coordinates:
  * samples    (samples) int64 0 1 2 3 4 ... 4846487 4846488 4846489 4846490
  * timesteps  (timesteps) int64 0 1 2 3 4 5 6 7 8 9
  * features   (features) object 'A+IGBT-I: current' ... 'DV/DT'

In [524]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler






<xarray.DataArray (samples: 4846491, features: 2)>
array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])
Coordinates:
  * samples   (samples) int64 0 1 2 3 4 ... 4846487 4846488 4846489 4846490
  * features  (features) object 'Class_Fault' 'Class_Run'

In [473]:
x_train, x_test, y_train, y_test = train_test_split(inputs, outputs, test_size=0.3)



In [474]:
x_train_scaled, x_test_scaled, x_scaler = scale_data(x_train, x_test, scaler=MinMaxScaler())



In [475]:
y_train_scaled, y_test_scaled, y_scaler = scale_data(y_train, y_test, scaler=MinMaxScaler())

In [476]:
%%time


x_train_sampled = x_train_scaled[:2000]  
y_train_sampled = y_train_scaled[:2000]

x_test_sampled = x_test_scaled[:800]
y_test_sampled = y_test_scaled[:800]


CPU times: user 320 µs, sys: 4.16 ms, total: 4.48 ms
Wall time: 4.49 ms


In [477]:
x_train_sampled.shape

(2000, 10, 14)

In [512]:
y_train_sampled.shape

(2000, 2)

In [532]:
lstm_structure = {

    "LSTM": {
        "num_layers": mai.Int(min_value=0, max_value=3),
        "units": mai.Int(min_value=20, max_value=100),
        "activation": "tanh",
        "recurrent_activation": "sigmoid",
        "recurrent_dropout": mai.Choice([0.0, 0.2, 0.4, 0.6]),
        "return_sequences": True,
    },

    "Dense": {
        "units": y_train_sampled.shape[1],
        "activation": "softmax",
    }
}


fitting = {
    "batch_size": 512,
    "epochs": 5,
    "validation_split":0.15,
    "callbacks": [
        ReduceLROnPlateau(
            monitor='val_mean_absolute_error',
            factor=0.8,
            patience=2,
            min_lr=0,
            verbose=1,
        ),
        EarlyStopping(
            monitor="val_mean_absolute_error",
            patience=3,
        )
    ]
}
adam = {
    "learning_rate": mai.Float(min_value=0.00001, max_value=0.001),
    "clipnorm": mai.Float(min_value=0.8, max_value=1.2),
    "clipvalue": mai.Float(min_value=0.3, max_value=0.7),
}
compiling = {
    "loss": "mean_absolute_error",
    "metrics": ["mean_absolute_error"],
}

model_settings = {
    "models": ["LSTM"],
    "LSTM": {
        "structural_params": lstm_structure,
        "optimizer": "Adam",
        "Adam": adam,
        "compile_params": compiling,
        "fitting_params": fitting,
    },
}
tuner = mai.Tuner(x_train_sampled, y_train_sampled, model_settings=model_settings)

In [533]:
x_train_sampled.shape

(2000, 10, 14)

In [534]:
lstm_structure

{'LSTM': {'num_layers': <pyMAISE.utils.hyperparameters.Int at 0x7968e8195790>,
  'units': <pyMAISE.utils.hyperparameters.Int at 0x7968e8232450>,
  'activation': 'tanh',
  'recurrent_activation': 'sigmoid',
  'recurrent_dropout': <pyMAISE.utils.hyperparameters.Choice at 0x7968e83dd1d0>,
  'return_sequences': True},
 'Dense': {'units': 2, 'activation': 'softmax'}}

In [535]:
y_train_sampled.shape

(2000, 2)

In [536]:

start = time.time()

bayesian_search_configs = tuner.nn_bayesian_search(
    objective="accuracy_score",
    max_trials=10,
    cv=2,
)

print("Hyperparameter tuning took " + str((time.time() - start) / 60) + " minutes to process.")


Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
3                 |3                 |LSTM_num_layers
0.00041691        |0.00041691        |Adam_learning_rate
0.91215           |0.91215           |Adam_clipnorm
0.3762            |0.3762            |Adam_clipvalue



Traceback (most recent call last):
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacc/pyMAISE/pyMAISE/utils/cvtuner.py", line 91, in run_trial
    self.hypermodel.fit(
  File "/home/jacc/pyMAISE/pyMAISE/methods/nn/_nn_hypermodel.py", line 142, in fit
    return model.fit(
           ^^^^^^^^^^
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/tensorf

RuntimeError: Number of consecutive failures exceeded the limit of 1.
Traceback (most recent call last):
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jacc/pyMAISE/pyMAISE/utils/cvtuner.py", line 91, in run_trial
    self.hypermodel.fit(
  File "/home/jacc/pyMAISE/pyMAISE/methods/nn/_nn_hypermodel.py", line 142, in fit
    return model.fit(
           ^^^^^^^^^^
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    except TypeError as e:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node gradient_tape/mean_absolute_error/sub/BroadcastGradientArgs defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/asyncio/events.py", line 80, in _run

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code

  File "/tmp/ipykernel_2548977/4130447353.py", line 3, in <module>

  File "/home/jacc/pyMAISE/pyMAISE/tuner.py", line 894, in nn_bayesian_search

  File "/home/jacc/pyMAISE/pyMAISE/tuner.py", line 1038, in _nn_tuning

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 234, in search

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial

  File "/home/jacc/pyMAISE/pyMAISE/utils/cvtuner.py", line 91, in run_trial

  File "/home/jacc/pyMAISE/pyMAISE/methods/nn/_nn_hypermodel.py", line 142, in fit

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/engine/training.py", line 1807, in fit

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/engine/training.py", line 1401, in train_function

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/engine/training.py", line 1384, in step_function

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/engine/training.py", line 1373, in run_step

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/engine/training.py", line 1154, in train_step

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 543, in minimize

  File "/home/jacc/anaconda3/envs/tf2.15/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 276, in compute_gradients

Incompatible shapes: [512,10,2] vs. [512,2]
	 [[{{node gradient_tape/mean_absolute_error/sub/BroadcastGradientArgs}}]] [Op:__inference_train_function_16372296]


In [ ]:
x_train_scaled

In [ ]:
y_train_scaled.shape

In [ ]:


# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [ ]:

quick_history = model.fit(
    x_train_sampled,
    y_train_sampled,
    epochs=100,
    batch_size=256,  
    validation_data=(x_test_sampled, y_test_sampled)
)


In [ ]:
test_loss, test_accuracy = model.evaluate(x_test_sampled, y_test_sampled)

In [ ]:
print("Test Loss: {:.4f}".format(test_loss))
print("Test Accuracy: {:.2f}%".format(test_accuracy * 100))

In [ ]:
x_train.size


In [ ]:
plt.plot(quick_history.history['loss'], label='Training loss')
plt.plot(quick_history.history['val_loss'], label='Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.title('Training vs Validation Loss')
plt.show()

In [ ]:
plt.plot(quick_history.history['accuracy'], label='Training accuracy')
plt.plot(quick_history.history['val_accuracy'], label='Validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training vs Validation Accuracy')
plt.show()

In [ ]:
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


y_test_sampled_np = y_test_sampled.values 

y_true_classes = np.argmax(y_test_sampled_np, axis=1)

y_pred_prob = model.predict(x_test_sampled.values) 

y_pred_classes = np.argmax(y_pred_prob, axis=1)


cm = confusion_matrix(y_true_classes, y_pred_classes)


disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap=plt.cm.Blues)
plt.show()

In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_true_classes, y_pred_prob[:, 1])
roc_auc = auc(fpr, tpr)

# Plot the ROC curve
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = {:.2f})'.format(roc_auc))
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()